# Generated by Django 4.2 on 2024-01-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=50)),
                ('domrg', models.CharField(max_length=50)),
            ],
        ),
    ]
